### ISSUE TITLE
SMB1 savestates not working on PS3

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-fceumm#191]
Basically loading a state on PS3 does exactly nothing in SMB1, I guess it may affect other games that use the same mapper

- Load FCEUMM
- Load Super Mario Bros. (World)
- Do stuff
- Save a state
- Try to load the state

**Comment by retro-wertz** [comment]
im not having any luck here. found test roms that are mapper 0 and those works with save states. the save states themselves works fine if your transfer that to other platforms, or you transfer save state from other platform, so something related to "loading states" is the issue here.

there's a wii port based on fceux and those worked with mapper 0 save state loading(using wiiu).
