### ISSUE TITLE
(FDS) Allow disc changing

### ISSUE THREAD

**Issue by Oggom** [libretro/libretro-fceumm#2]
It's currently not possible to switch disk sides when playing FDS games, rendering many of them unplayable.

**Comment by digitalLumberjack** [comment]
I'm stuck with that too ...

**Comment by twinaphex** [comment]
I'll take a look at this soon.

BTW digitalLumberJack, now that I have you here, I have serious issues with you using 'RetroBox OS' (of all things) as the name for your distro. I find it very hard to believe you were not aware of our intention to use that name for our own project and it starts feeling even more offensive when this then gets attached to a $150 Raspberry Pi selling venture. I don't have issues with you selling this device just for the record, I have issues with the name being 'RetroBox' so that we now have to go about our way coming up with a different name because the 'RetroBox' name has already been appropriated by a dozen other guys selling some similar venture. And to add offense to injury now you also expect us also to support you.

Anyway, the 'RetroBox' name is trademarked by some other guy since 2006, so we were never able to use that name anyway. So you might as well start doing it exactly like us and rename it before the rights holder comes down on you.

**Comment by digitalLumberjack** [comment]
Hi, twinapex. I sent a mail to libretro@gmail.com

We might discuss by email if you don't mind.

**Comment by digitalLumberjack** [comment]
For the record, i'm changing the name of the project used to be called retrobox. 

So about this bug, i tried the nestopia core and i saw you use L and R to eject and swap disk. And i tested some games, it does work this way.

**Comment by bmosley** [comment]
Is this still being considered? I would love to be able to use this in fceumm core and basically all games I've tested have been hit by this blocker.

**Comment by Oggom** [comment]
Closed due https://github.com/libretro/libretro-fceumm/pull/29
