### ISSUE TITLE
FDS sound issue

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/libretro-fceumm#210]
Zelda no densetsu has some sound issues, particularly noticeable on the effect when you die.

win7 x64 current RA nightly, every sound option

**Comment by riggles1** [comment]
Ah, now I find it, after posting my issue: https://github.com/libretro/libretro-fceumm/issues/560 

Yeah FDS audio is in a terrible state sadly, can't wait for it to get a fix some day.

**Comment by negativeExponent** [comment]
dunno why this was closed. but might want test latest commit if FDS audio is better than before.

**Comment by Tatsuya79** [comment]
Maybe it's fine? It's hard to tell as every other emu sounds different.

Close enough to that:

**Comment by riggles1** [comment]
> dunno why this was closed. but might want test latest commit if FDS audio is better than before.

Sounds good now, absolute hero! Not to be harsh but it was hilarious before lol. It was a shame since it was to the point where you'd find many top result FDS gameplay videos with completely wrong note pitches.
https://youtu.be/idyTM6zeGjk?si=6eIMDPLbqTlzDVxk

This emu was done Soyo Oka (vs excitebike above) dirty, until now! This is amazing, fceux/mm is great for being so lightweight and everything, so I'm stoked to see this. Thank you! :D
