### ISSUE TITLE
FCEUmm and Arkanoid ROM

### ISSUE THREAD

**Issue by Diegus83** [libretro/libretro-fceumm#308]
I know this has been asked before [here](https://github.com/libretro/libretro-fceumm/issues/230) but the proposed solution hasn't worked for me.
I'm running FCEUmm in Recalbox on a raspberry pi 3. The controller I'm using is an 8bitdo bt controller with both d-pad and two sticks. When I enter the retroarch menu the version I see on the lower left side is "1.8.1 - FCEUmm ((SVN) 25c5a8b4de)
I have an arkanoid (US) rom from a No-Intro rom set and I have already set the User 1 Device Type to "gamepad" under "quick menu, controls" but I still can't control the paddle. Tried both the d-pad and analog sticks and also setting the "User 1 Analog to Digital Type" to left, right and none.
Any ideas how to solve this? The final goal is to be able to play using the d-pad.
Thanks!

**Comment by negativeExponent** [comment]
if using the US rom (NES), set User 2 to NONE instead of auto. if using the Japan rom (Famicom), disable User 5 instead.

Further explanation:
- on NES, player 2 port acts as expansion port, including arkanoid paddle in this case (using mouse)
- on Famicom (when loading Japanese ROMS), expansion port is on a dedicated port which is mapped to User 5 on fceumm.

this should resolve this issue and any other confusion with nes/famicom expansions

**Comment by Diegus83** [comment]
Thanks so much!

Been looking for a solution for a while, I should have come straight to the source in the first place.

Is there a wiki or any other place where information like this is contained? I mean special cases like Arkanoid and other roms that have special characteristics.

**Comment by negativeExponent** [comment]
> Thanks so much!
> 
> Been looking for a solution for a while, I should have come straight to the source in the first place.
> 
> Is there a wiki or any other place where information like this is contained? I mean special cases like Arkanoid and other roms that have special characteristics.

we have a general documents page https://docs.libretro.com/, but it probably do have have this info in details there
