### ISSUE TITLE
Games that doesn't work (RPi2)

### ISSUE THREAD

**Issue by LodanZark** [libretro/libretro-fceumm#38]
no-intro roms:
Field Combat (Japan) - CRC32: F0A8371E
Galaxian (Japan) (Rev A) - CRC32: A80DA263
King Neptune's Adventure (USA) (Unl) - CRC32: AE4B13DF

Translations Hacks:
Kero Kero Keroppi's Big Adventure (http://www.romhacking.net/translations/165/) - CRC32: 0DFBDA9C
Legend of Future: Jarvas (http://www.romhacking.net/translations/1275/) CRC32: 85F6D496
Popeye's Lingo (http://www.romhacking.net/translations/785/) CRC32: F30941DB
Samurai Pizza Cats (Samurai Pizza Cats v1.01.xdelta)(http://www.romhacking.net/translations/1741/) CRC32: 60F29773
Higemaru: Seven Islands Adventure (http://www.romhacking.net/translations/1278/) CRC32: 9E06879B

**Comment by retro-wertz** [comment]
for 1, Galaxian is a bad rom dump(or somewhat), not all verified by no-intro is confirmed to run.  the Goodnes version of it runs, even if it is labeled "overdumped"
King Nepture should also be on the same boat as galaxian, as it also does not run(even on standlone fcumm/fceux)

the translation hacks are just probably wrong crc files to begin with, or now has missing or invalid headers.

this can be probably be closed now? since its been a year already :D
