### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/libretro-fceumm#427]
Well could you start to use versions like `Major.Minor.Patch` for your releases?

**Comment by SupervisedThinking** [comment]
Closed since proper versioning is considered as spam & trolling.

**Comment by keithbowes** [comment]
Officially, the version has been 0.98.13 since 2014, but so much progress has been made that it should be at least 0.99.0 by now.  I don't know why they shortly replaced it by (SVN), as the upstream SVN repo doesn't even exist anymore, but the lack of correctly identified stable versions is why I gravitate to other NES cores.

**Comment by negativeExponent** [comment]
> Officially, the version has been 0.98.13 since 2014, but so much progress has been made that it should be at least 0.99.0 by now. I don't know why they shortly replaced it by (SVN), as the upstream SVN repo doesn't even exist anymore, but the lack of correctly identified stable versions is why I gravitate to other NES cores.

im not sure how hard you looked, but:
https://sourceforge.net/projects/fceumm/
