### ISSUE TITLE
RetroArch Crashing when enabling overclock option in FCEUmm core! 

### ISSUE THREAD

**Issue by blackman91** [libretro/libretro-fceumm#58]
Resposted from here:
https://github.com/libretro/RetroArch/issues/4363#issuecomment-270558175

**Comment by meepingsnesroms** [comment]
This happened to me today too,this option should only be checked on reboot.(the NES is designed to have a fixed clock speed)

If you turn overclock on then close the game and exit retroarch with the exit menu option then reload the game overclock will be working fine.

This is likely because the core has some fixed speed values so they can only be set before starting a ROM.

**Comment by blackman91** [comment]
But the crash didn't happen in previous version of the core.

**Comment by JacobAL** [comment]
I get a crash even if I just choose to exit retroarch after setting the option.
1.4.1.

**Comment by blackman91** [comment]
Here is a previous version of the core that didn't crash when enabling overclock:

[fceumm_libretro_android.so.zip](https://github.com/libretro/libretro-fceumm/files/785914/fceumm_libretro_android.so.zip)

**Comment by retro-wertz** [comment]
i do not know how this is suppose to work(i mean should correctly work) but it looks like after setting overclock, do not resume game. instead close core and just relaunch.

**Comment by retro-wertz** [comment]
lets continue this discussion in the other thread.... 

https://github.com/libretro/libretro-fceumm/issues/73

request for thread close?

**Comment by blackman91** [comment]
Tested latest on android, enabling overclock no longer crashes retroarch, nice job man! You can close all those issues.
