### ISSUE TITLE
Raw palette doesn't handle emphasis correctly

### ISSUE THREAD

**Issue by Patchy68k** [libretro/libretro-fceumm#615]
Emphasis bits don't work right with the raw palette. This becomes very obvious when trying to play The Immortal with my patchy-mesen-raw-palette shader preset. In fact, this issue is exactly the reason why that preset has "Mesen" in its name.

I will upload a screenshot of this later.

**Comment by Patchy68k** [comment]
My memory was wrong. The shader that wasn't working with FCEUmm was GTU-Famicom, not Patchy-NTSC. By adding a small fix to GTU-Famicom, I was able to make its output look better.

Still, the raw palette in FCEUmm is different from the raw palette in Mesen, and it is causing different results in Patchy-NTSC. I don't know which emulator's output is correct.

FCEUmm's output for The Immortal:
![fceumm_raw](https://github.com/user-attachments/assets/5a9f0ed9-de41-43c5-bc84-e677230ccd2c)

Mesen's output for The Immortal:
![mesen_raw](https://github.com/user-attachments/assets/3a9f1e07-6443-4bbe-a069-4049e9c53ccb)

FCEUmm's output decoded by patchy-color:
![fceumm_raw_decoded](https://github.com/user-attachments/assets/2d4ffff6-d2e0-4295-9c8d-74c0f869678a)

Mesen's output decoded by patchy-color with the exact same settings:
![mesen_raw_decoded](https://github.com/user-attachments/assets/214fd828-7e94-4b88-8259-7802c2222201)

These two emulators' raw palettes are slightly different from each other. Decoding FCEUmm's gives brighter colors than Mesen's.

Here are the settings I used with patchy-color which you can use to replicate this output. Just beware that patchy-color is going to get an update soon that's going to change its output significantly.

pc_console = "2.000000"
pc_nes_lut = "1.000000"
pc_contrast = "1.000000"
pc_brightness = "0.100000"
lut_toggle = "0.000000"
lut_index = "0.000000"

**Comment by negativeExponent** [comment]
deephs are fetched differently in fceu-based cores since palette is packed into an 8bit per pixel including deemp while traditionally palettes are 9bit, with 6bit palette and 3 bit emphasis.

fceu-xx fetches color like this:
`out = palette_table[pixel & 0x3f] | (deemp << 2)`
while traditionally deempasis is fetched directly from the palette table itself
`out = palette_table[(pixel & 0x3f) | (deemp << 6)`

if probably fixable by writing raw palette into a 512 palette table instead of the current 256. non deeph colore will fetch from the original palette table, probably offset 0, and with deephasis using the color emphasis table like offset 256 from the same table.

BUT since pixel and the pixel deemphasis are on 2 different pointers, i dont know how to apply it into one pointer for use on PS2 and PSP branch without having to rewrite both into another table which will probably cause yet more performance hit for those platforms.

**Comment by negativeExponent** [comment]
something like this:

https://github.com/negativeExponent/libretro-fceumm/tree/palette_deemp_512

see if that works differently.

**Comment by hizzlekizzle** [comment]
so, how would someone generate a palette of the new size? Or, the more likely situation, convert an existing 256 palette to 512?

We got a guy on discord who mentioned that his custom palette image went from:
https://cdn.discordapp.com/attachments/469974542299955210/1308912582827970601/image.png?ex=673fab56&is=673e59d6&hm=b98c43b030de5637dd648fc278315a199f9f4f1e57ffa9136bf314bcaa9eef8d&

to

https://cdn.discordapp.com/attachments/469974542299955210/1308912583306383380/image.png?ex=673fab56&is=673e59d6&hm=336a6eb5a4aa632b2e9d7246a2bcfc23db8f1661a6995fa2c84698e48649176a&

after updating. Do any existing palette tools work with the 512 palette size?

**Comment by negativeExponent** [comment]
Is he using 512 palette? Is so he probably genetaed his emphis wrong for fcueXx.

Have him strip down his palette into the base palette of 3x64 palette file and load it as custom nes.pal. this should load it and internally create the appropriate full palette.
