### ISSUE TITLE
fceumm lags on old 3DS XL

### ISSUE THREAD

**Issue by dkl3** [libretro/libretro-fceumm#90]
Hi, any idea why fceumm lags on an old 3DS XL? for some reason when I try it on old 3DS the games just lag...?

**Comment by fr500** [comment]
well... the o3ds is slow....

**Comment by meepingsnesroms** [comment]
Ps2 games lag on my 2016 android phone too, thats not a bug just an old device and unoptimized emulator.

We cant fix this, there is no 3dsBeSlow = 1; that can be changed to make it fast.

Change these settings for a minor boost:
Disable sprite limit = true
Overclocking = false

I dont have a 3ds so I cant give system specific suggestions.

The 3ds has the cpu specs of half a 2008 android phone so this is to be expected.(Gpu does not count since the 2d emulators dont use then, extra cpus also dont count since the nes only had one cpu and everything is done in order)
